@api_url = http://localhost:5002/api
@token = 

GET {{api_url}}/bookings/user-info
Authorization: Bearer {{token}}

###

GET {{api_url}}/bookings
Authorization: Bearer {{token}}

###

GET {{api_url}}/bookings/08dd8a5f-3b4d-47df-8f1b-3213fcbd6de4
Authorization: Bearer {{token}}

###

POST {{api_url}}/bookings/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "offerId": "08dd8a86-751d-4036-8dd5-a8063bae6bc1",
  "seatNumber": "20A",
  "seatType": 1,
  "passengerName": "John Traveller",
  "passengerType": 2
}

###

DELETE {{api_url}}/bookings/08dd8a5f-3b4d-47df-8f1b-3213fcbd6de4
Authorization: Bearer {{token}}