@api_url = http://localhost:5002/api
@token =

GET {{api_url}}/Booking/user-info
Authorization: Bearer {{token}}

###

GET {{api_url}}/Booking
Authorization: Bearer {{token}}

###

GET {{api_url}}/Booking/08dd8a5f-3b4d-47df-8f1b-3213fcbd6de4
Authorization: Bearer {{token}}

###

POST {{api_url}}/Booking/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "offerId": "007a4ecb-8b0e-4278-bbba-62d748841a05",
  "seatNumber": "20A",
  "seatType": 2,
  "passengerName": "John Traveller",
  "passengerType": 0
}

###

DELETE {{api_url}}/Booking/08dd8a5f-3b4d-47df-8f1b-3213fcbd6de4
Authorization: Bearer {{token}}