services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"

  mariadb:
    container_name: admin-mysql_db
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "student"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  travelmatefrontend:
    container_name: TravelMateFrontend
    build:
      context: ./travelmate-userapp
    ports:
      - "4200:80"
    environment:
      OFFERS_API_URL: "http://travelmateofferservice:8080/api"
      AUTH_API_URL: "http://travelmateauthservice:8080/api"
      BOOKING_API_URL: "http://travelmatebookingservice:8080/api"
      PAYMENT_API_URL: "http://travelmatepaymentservice:8080/api"
    depends_on:
      - travelmateofferservice
      - travelmateauthservice
      - travelmatebookingservice
      - travelmatepaymentservice

  travelmateofferservice:
    container_name: TravelMateOfferService
    build:
      context: ./TravelMateOfferService
    ports:
      - "5000:8080"
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  travelmateauthservice:
    container_name: TravelMateAuthService
    build:
      context: ./TravelMateAuthService
    ports:
      - "5001:8080"
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  travelmatebookingservice:
    container_name: TravelMateBookingService
    build:
      context: ./TravelMateBookingService
    ports:
      - "5002:8080"
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  travelmatepaymentservice:
    container_name: TravelMatePaymentService
    build:
      context: ./TravelMatePaymentService
    ports:
      - "5003:8080"
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  travelmatesagaorchestrator:
    container_name: TravelMateSagaOrchestrator
    build:
      context: ./TravelMateSagaOrchestrator
    ports:
      - "5004:8080"
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_started

volumes:
  mariadb_data:
