services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "student"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  travelmateofferservice:
    container_name: TravelMateOfferService
    build:
      context: ./TravelMateOfferService
    ports:
      - "18859:8080"
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  travelmateauthservice:
    container_name: TravelMateAuthService
    build:
      context: ./TravelMateAuthService
    ports:
      - "18860:8080"
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
volumes:
  mariadb_data:
