@api_url = http://localhost:5001/api

POST {{api_url}}/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

POST {{api_url}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}